In [7]:
import numpy as np
from skimage.feature import peak_local_max

img = np.random.rand(2000, 2000)

# peaks = peak_local_max(img, threshold_abs=0, num_peaks=2000)

# len(peaks)

# ps = [np.ravel_multi_index(p, img.shape) for p in peaks]
# img.flat[ps] > 0.5


# img[peaks.T[0], peaks.T[1]].shape

# img[tuple(map(list, peaks.T))].shape

from src.calmutils.localization import detect_dog, refine_point


peaks = detect_dog(img, 0, threshold_intensity=0.5, sigma=1, max_num_peaks=100)

[refine_point(img, p) - p for p in peaks]
# peaks

[array([-0.00416723, -0.16625828]),
 array([-0.33023903, -0.2853456 ]),
 array([0.07858541, 0.        ]),
 array([ 0.5165533 , -0.02748527]),
 array([ 0.27798004, -0.09768099]),
 array([-1,  1]),
 array([ 0.56899924, -2.16218627]),
 array([0.37700914, 0.26177414]),
 array([ 1, -1]),
 array([-2.18147795, -0.33767115]),
 array([-0.06333094, -0.0006067 ]),
 array([0.67916958, 1.9779643 ]),
 array([-0.43753928, -0.55570998]),
 array([-0.0053765 ,  0.03809361]),
 array([-0.56141362,  0.04201614]),
 array([ 3.24462623, -3.21857407]),
 array([-0.32493729, -0.07937941]),
 array([ 0.3215719 , -0.26186137]),
 array([0.3420791 , 0.29625242]),
 array([ 0.19650274, -0.13392608]),
 array([ 0.4018184 , -0.10308318]),
 array([1, 1]),
 array([-0.1449674 , -0.15549754]),
 array([0.17521305, 0.12782644]),
 array([0.00038164, 0.21378245]),
 array([0.55665815, 0.11240643]),
 array([0.04388298, 0.21223977]),
 array([0.06457117, 0.2675683 ]),
 array([ 0.24986575, -0.08087302]),
 array([ 0.86241938, -2.704965

In [7]:
[1, 2, 3][slice(None, -1)]

[1, 2]

In [3]:
from calmutils.misc.bounding_boxes import transpose_bboxes, minmax_to_minlen_bboxes

mins = [0, 1, 2]
maxs = [4, 5, 6]

transpose_bboxes(*minmax_to_minlen_bboxes(mins, maxs))

(array([0, 4]), array([1, 4]), array([2, 4]))

In [7]:
from calmutils.stitching.tiling import centered_tiles, minmax_tiles

centered_tiles([0,0], [1,1], 3, flip_axes=(1,))

minmax_tiles([1, 1], [-1, -1], 1, flip_axes=(1,))

array([[-1.,  1.],
       [-1.,  0.],
       [-1., -1.],
       [ 0., -1.],
       [ 0.,  0.],
       [ 0.,  1.],
       [ 1.,  1.],
       [ 1.,  0.],
       [ 1., -1.]])